#cloud-config
apt_mirror: http://mirror.rackspace.com/ubuntu/
package_upgrade: true
packages:
  - git-core
  - screen
  - vim
runcmd:
  - export ANSIBLE_FORCE_COLOR=true
  - export PYTHONUNBUFFERED=1
  - export REPO=https://github.com/rcbops/rpc-openstack
  - export TAG=master
  - export DEPLOY_AIO=yes
  - git config --global user.email "miguel.cantu@rackspace.com"
  - git config --global user.name "Miguel Alex Cantu"
  - curl http://paste.openstack.org/raw/532108/ >> /root/.ssh/authorized_keys
  - git clone -b ${TAG} --recursive ${REPO} /opt/rpc-openstack
  - bash /tmp/configure_nfs.sh

output: { all: '| tee -a /var/log/cloud-init-output.log' }
