#cloud-config
apt_mirror: http://mirror.rackspace.com/ubuntu/
package_upgrade: true
packages:
  - git-core
runcmd:
  - export ANSIBLE_FORCE_COLOR=true
  - export PYTHONUNBUFFERED=1
  - export REPO=https://github.com/openstack/openstack-ansible
  - export BRANCH=master
  - export ANSIBLE_ROLE_FETCH_MODE=git-clone
  - git clone -b ${BRANCH} ${REPO} /opt/openstack-ansible
  - bash /tmp/configure_nfs.sh
output: { all: '| tee -a /var/log/cloud-init-output.log' }
