#cloud-config
apt_mirror: http://mirror.rackspace.com/ubuntu/
package_upgrade: true
packages:
  - git-core
  - screen
  - vim
runcmd:
  - git clone https://github.com/alextricity25/osa-multi-node-aio.git /root/osa-multi-node-aio
  - git config --global user.email "miguel.cantu@rackspace.com"
  - git config --global user.name "Miguel Alex Cantu"
  - cd /root/osa-multi-node-aio && ./build.sh
output: { all: '| tee -a /var/log/cloud-init-output.log' }
